#!/bin/bash
set -e
app=kodi

# Source app helpers
	source /usr/share/yunohost/helpers

# The parameter $1 is the backup directory location which will be compressed afterward
	backup_dir=$1/apps/$app
	sudo mkdir -p $backup_dir

# Copy the app source files
	#DESTDIR="/var/www/$app"
	#ynh_backup "$DESTDIR" "www"
	
# Copy the conf files
	mkdir ./conf
	ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "conf/nginx.conf"
	ynh_backup "/etc/apt/sources.list.d/${app}.list" "conf/${app}.list"
	ynh_backup "/etc/systemd/system/${app}.service" "conf/${app}.service"
	ynh_backup "/usr/share/kodi/userdata/advancedsettings.xml" "conf/advancedsettings.xml"

# Dump the database
	#mysqldump -u "$dbuser" -p"$dbpass" --no-create-db "$dbname" > ./db.sql
