#!/bin/bash
set -e
app=kodi

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)

# Remove service
	sudo yunohost service stop $app
	sudo yunohost service disable $app
	sudo yunohost service remove $app
	sudo rm /etc/systemd/system/$app.service
	
# Uninstall Kodi
	ynh_package_remove kodi

# Delete userdata folder?
	
# Remove configuration files
	sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# If a database is used, remove it
	#ynh_mysql_drop_db "$dbname" 2>/dev/null || true
	#ynh_mysql_drop_user "$dbuser" 2>/dev/null || true

# Restart services
	sudo service nginx reload || true
