#!/bin/bash
app=kodi

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)

# Remove service
	sudo yunohost service stop kodi
	sudo yunohost service disable kodi
	sudo yunohost service remove kodi
	sudo rm /etc/systemd/system/kodi.service
	sudo rm /etc/init.d/kodi
	
# Uninstall Kodi
	sudo apt-get remove -y kodi

# Delete userdata folder?
	
# Remove configuration files
	#sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# If a database is used, remove it
	# root_pwd=$(sudo cat /etc/yunohost/mysql)
	# mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf
