#!/bin/bash
set -e
app=kodi

# Source app helpers
	source /usr/share/yunohost/helpers
	
# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	
# Check domain/path availability
	sudo yunohost app checkurl $domain$path -a ${app} \
	|| (echo "Path not available: $domain$path" && exit 1)
	
# Check port availability
	sudo yunohost app checkport 8066
	if [[ ! $? -eq 0 ]]; then
	  exit 1
	fi
	
# Reinstall kodi
	sudo cp -a ./conf/${app}.list "/etc/apt/sources.list.d/${app}.list"
	ynh_package_update
	ynh_package_install kodi

# Restore service
	sudo cp -a ./conf/${app}.service "/etc/systemd/system/${app}.service"
	sudo yunohost service add $app --log /var/log/$app.log
	sudo yunohost service enable $app
	sudo yunohost service start $app

# Restore web interface
	sudo cp -a ./conf/advancedsettings.xml "/usr/share/kodi/userdata/advancedsettings.xml"

# Restore Nginx
	sudo cp -a ./conf/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restore mysql database if needed
	# ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
	# ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./db.sql
	
# Restore user files: TBD

# Restart webserver
	sudo service nginx reload || true
