#!/bin/bash
set -e
app=kodi

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)

# Upgrade Kodi
	sudo cp ../conf/kodi.list /etc/apt/sources.list.d/kodi.list
	
	sudo yunohost service stop kodi
	sudo apt-get update
	sudo apt-get install -y kodi
	
	sudo cp ../conf/kodi.service /etc/systemd/system/kodi.service
	sudo cp ../conf/kodi.init /etc/init.d/kodi
	sudo chmod a+x /etc/init.d/kodi
	sudo yunohost service add kodi --log /var/log/kodi.log
	sudo yunohost service enable kodi
	sudo yunohost service start kodi
	
# Modify Nginx configuration file and copy it to Nginx conf directory
	sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf

